// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactFlipPage = require("react-flip-page");

function boolFromOpt(x) {
  if (x !== undefined) {
    return x;
  } else {
    return false;
  }
}

function make(animationDuration, className, disableSwipe, firstComponent, flipOnTouch, flipOnTouchZone, height, lastComponent, loopForever, maskOpacity, maxAngle, onPageChange, onStartPageChange, onStartSwiping, onStopSwiping, orientation, pageBackground, perspective, responsive, reverse, showHint, showSwipeHint, showTouchHint, startAt, style, swipeImmune, treshold, uncutPages, width, children) {
  return ReasonReact.wrapJsForReason(ReactFlipPage.default, {
              animationDuration: Js_undefined.fromOption(animationDuration),
              className: Js_undefined.fromOption(className),
              disableSwipe: boolFromOpt(disableSwipe),
              firstComponent: Js_undefined.fromOption(firstComponent),
              flipOnTouch: boolFromOpt(flipOnTouch),
              flipOnTouchZone: Js_undefined.fromOption(flipOnTouchZone),
              height: Js_undefined.fromOption(height),
              lastComponent: Js_undefined.fromOption(lastComponent),
              loopForever: boolFromOpt(loopForever),
              maskOpacity: Js_undefined.fromOption(maskOpacity),
              maxAngle: Js_undefined.fromOption(maxAngle),
              onPageChange: Js_undefined.fromOption(onPageChange),
              onStartPageChange: Js_undefined.fromOption(onStartPageChange),
              onStartSwiping: Js_undefined.fromOption(onStartSwiping),
              onStopSwiping: Js_undefined.fromOption(onStopSwiping),
              orientation: Js_undefined.fromOption(orientation),
              pageBackground: Js_undefined.fromOption(pageBackground),
              perspective: Js_undefined.fromOption(perspective),
              responsive: boolFromOpt(responsive),
              reverse: boolFromOpt(reverse),
              showHint: boolFromOpt(showHint),
              showSwipeHint: boolFromOpt(showSwipeHint),
              showTouchHint: boolFromOpt(showTouchHint),
              startAt: Js_undefined.fromOption(startAt),
              style: Js_undefined.fromOption(style),
              swipeImmune: Js_undefined.fromOption(swipeImmune),
              treshold: Js_undefined.fromOption(treshold),
              uncutPages: boolFromOpt(uncutPages),
              width: Js_undefined.fromOption(width)
            }, children);
}

exports.boolFromOpt = boolFromOpt;
exports.make = make;
/* ReasonReact Not a pure module */
